providers:
  deepseek-chat:
    display_name: deepseek-chat
    base_url: https://api.deepseek.com/v1
    model: deepseek-v4-flash
    api_format: deepseek
    enabled: true
    note:
    created_at: 2026-06-12 23:22:43
    updated_at: 2026-06-13 00:10:14
    rate_limit: 0
    deduplicate: true
  英伟达:
    display_name: 英伟达
    base_url: https://integrate.api.nvidia.com/v1
    model: deepseek-ai/deepseek-v4-flash
    api_format: openai
    enabled: true
    note:
    created_at: 2026-06-13 19:38:21
    updated_at: 2026-06-25 23:15:55
    rate_limit: 35
    deduplicate: true
  nvidia-v4-flash:
    display_name: nvidia-v4-flash
    base_url: https://integrate.api.nvidia.com/v1
    model: deepseek-ai/deepseek-v3.2
    api_format: openai
    enabled: true
    note:
    created_at: 2026-06-13 19:49:28
    updated_at: 2026-06-18 21:35:19
    rate_limit: 0
    deduplicate: true
  商汤科技:
    display_name: 商汤科技
    base_url: https://token.sensenova.cn/v1
    model: deepseek-v4-flash
    api_format: openai
    enabled: true
    note:
    created_at: 2026-06-13 20:26:45
    updated_at: 2026-06-25 23:16:36
    rate_limit: 30
    deduplicate: true
  智谱:
    display_name: 智谱
    base_url: https://open.bigmodel.cn/api/paas/v4
    model: "glm-4-flash,glm-4-air,glm-4-plus,glm-5.2"
    api_format: openai
    enabled: true
    note:
    created_at: 2026-06-13 20:38:23
    updated_at: 2026-06-25 23:16:15
    rate_limit: 30
    deduplicate: true
  agents ai:
    display_name: agents ai
    base_url: https://apihub.agnes-ai.com/v1
    model: "agnes-2.0-flash,agnes-image-2.0-flash,agnes-video-v2.0,agnes-r1-7b"
    api_format: openai
    enabled: true
    note:
    created_at: 2026-06-15 21:55:42
    updated_at: 2026-06-19 08:33:36
    rate_limit: 0
    deduplicate: true
  火山引擎:
    display_name: 火山引擎
    base_url: https://ark.cn-beijing.volces.com/api/coding/v3
    model: ep-20260528001214-5fc9g
    api_format: openai
    enabled: true
    note:
    created_at: 2026-06-15 21:58:41
    updated_at: 2026-06-25 23:16:26
    rate_limit: 30
    deduplicate: true
  codex公益:
    display_name: codex公益
    base_url: https://new.sharedchat.cc/codex
    model: gpt-5.5
    api_format: openai
    enabled: true
    note:
    created_at: 2026-06-19 08:08:51
    updated_at: 2026-06-19 08:08:51
    rate_limit: 0
    deduplicate: true
  agents aiimg:
    display_name: agents aiimg
    base_url: https://apihub.agnes-ai.com/v1/images/generations
    model: agnes-image-2.0-flash
    api_format: openai
    enabled: true
    note:
    created_at: 2026-06-19 20:10:21
    updated_at: 2026-06-19 20:10:21
    rate_limit: 0
    deduplicate: true
current_provider: 英伟达
proxy:
  host: 127.0.0.1
  port: 3000
  virtual_model: virtual-model
ui_settings:
  enabled_clis:
  proxy_host: 127.0.0.1
  proxy_port: 3000
  virtual_model: virtual-model
